CREATE TABLE `app_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(180) COLLATE utf8_unicode_ci NOT NULL,
  `username_canonical` varchar(180) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(180) COLLATE utf8_unicode_ci NOT NULL,
  `email_canonical` varchar(180) COLLATE utf8_unicode_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  `salt` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `last_login` datetime DEFAULT NULL,
  `locked` tinyint(1) NOT NULL,
  `expired` tinyint(1) NOT NULL,
  `expires_at` datetime DEFAULT NULL,
  `confirmation_token` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `password_requested_at` datetime DEFAULT NULL,
  `roles` longtext COLLATE utf8_unicode_ci NOT NULL COMMENT '(DC2Type:array)',
  `credentials_expired` tinyint(1) NOT NULL,
  `credentials_expire_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_88BDF3E992FC23A8` (`username_canonical`),
  UNIQUE KEY `UNIQ_88BDF3E9A0D96FBF` (`email_canonical`),
  UNIQUE KEY `UNIQ_88BDF3E9C05FB297` (`confirmation_token`)
) ENGINE=InnoDB AUTO_INCREMENT=332 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `app_user` 
(`id`,
`username`,
`username_canonical`,
`email`,
`email_canonical`,
`enabled`,
`salt`,
`password`,
`last_login`,
`locked`,
`expired`,
`expires_at`,
`confirmation_token`,
`password_requested_at`,
`roles`,
`credentials_expired`,
`credentials_expire_at`)
VALUES (
'12', 
'admin',
 'admin',
 'admin@example.com',
 'admin@example.com',
 '1',
 '857w5i4j55gcw00wg0s48kgg8sg8ck0',
 '$2y$13$L/k8uze.FQSeCdw44l.h8.ro8IvN9N2thKrbhtGBZEZkw7CrVyV7e',
 '2016-12-26 14:23:47',
 '0',
 '0',
 NULL,
 NULL,
 NULL,
 'a:1:{i:0;s:16:\"ROLE_SUPER_ADMIN\";}',
 '0',
 NULL
 );
